### ISSUE TITLE
Errors on .live are uncatchable

### ISSUE THREAD

**Issue by ProbablePrime** [ExoZoneDev/wsabi-client#1]
I'd like to be able to catch error messages that come from the server on a call to .live

I was making a silly mistake, (omitting one set of :'s from a slug) on call to .live

```
wsabi.live(`user:000update`).subscribe(....)
```

And there's currently no way to catch or even investigate a failed promise from a call to .live. 

https://github.com/ExoZoneDev/wsabi-client/blob/master/src/client.js#L100 doesn't expose the promise back to the implementation. 

The same problem doesn't occur with .put,.get etc as the request promises are returned. 

I'm not sure on the best way to resolve this without breaking existing API so i'm opening an issue. For now I've got a rejection handler and some console.logs manually inserted within my projects `node_modules/` not ideal.

**Comment by artdude543** [comment]
Yeah this would be a good idea to get added. We're welcome to PR's and such. The client is still in early dev so not all the features / code base are added. But feel free to help out :)

**Comment by jamesbirtles** [comment]
Yeah this is one major flaw with the way I decided to implement this. Only immediate thoughts are some event emitted on error or perhaps another observable to subscribe to errors but that means the error handling is disconnected from the action itself. I might have to look more into observables and see if there is a mechanism there that would solve this.

**Comment by jamesbirtles** [comment]
This is now possible in [1.1.0](https://github.com/ExoZoneDev/wsabi-client/tree/1.1.0).
Example:

``` typescript
wsabi.live(`user:000:update`).subscribe(
  update => console.log(update),
  err => console.error(err)
)
```
