### ISSUE TITLE
204 statuses

### ISSUE THREAD

**Issue by ProbablePrime** [ExoZoneDev/wsabi-client#4]
As beam now uses 204 status codes 
https://github.com/ExoZoneDev/wsabi-client/blob/master/ts/src/client.ts#L52

Will reject on some requests.

**Comment by artdude543** [comment]
Well 204 is no content? What endpoints are using that now? This client is not just for Beam also. It's got compatible for other live sockets also. So we have to account for them also.

**Comment by artdude543** [comment]
Don't worry I got an insight to what's going to change. >.> Will fix soon ish.

**Comment by ProbablePrime** [comment]
:)
